version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    volumes:
      - ./api/app:/home/app
    ports:
      - 8000:8000
  db:
    image: mysql:8.0.29-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: development-database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.dev
    container_name: react-app
    volumes:
      - ./frontend/app:/user/src/app
    ports:
      - 3000:3000